--- #YAML:1.0
name:               PDF-TextBlock
version:            0.03
abstract:           Easier creation of text blocks when using PDF::API2
author:
    - Jay Hannah <jay@jays.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Accessor::Fast:  0
    File::Temp:           0
    PDF::API2:            0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
